#!/bin/bash

# fast keyrepeats
defaults write NSGlobalDomain KeyRepeat -int 0

# disable natural scrolling
defaults write NSGlobalDomain com.apple.swipescrolldirection -bool false

# screenshots in png format
defaults write com.apple.screencapture type -string "png"

# secure empty trash
defaults write com.apple.finder EmptyTrashSecurely -bool true
